# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"
# Uncomment this line if you"re using Swift
# use_frameworks!
platform :ios, "8.0"
inhibit_all_warnings! # this will disable all the warnings for all pods

target "Demo" do
    pod "TestClass", :path => ‘./Vendor/TestClass’, :configurations => ["Debug"]
end
